# Use the official Node.js image as the base image
FROM node:16

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the entire project to the container
COPY . .

# Build the TypeScript files
RUN npm run build

# Expose the port on which the application will run (make sure it matches the port used in server.ts)
EXPOSE 3000

# Start the application in production mode
CMD ["node", "lib/server.js"]
